apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snapshot-controller
  labels:
    app: snapshot-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      containers:
      - name: snapshot-controller
        image: quay.io/linki/snapshot-controller:v0.2.1
        args:
        - --project=some-project
        - --zone=europe-west1-d
        - --in-cluster
        - --interval=1h
        - --retain=48
